MODEL_FILE <- "EnergyPulse_Decision_Tree.rds"

predict_energy <- function(input_data) {
  if (!file.exists(MODEL_FILE)) {
    return(list(
      status = "model_unavailable",
      error = paste(
        "Model file not found. Add", MODEL_FILE,
        "to the backend folder."
      )
    ))
  }

  model <- tryCatch(
    readRDS(MODEL_FILE),
    error = function(e) e
  )

  if (inherits(model, "error")) {
    return(list(
      status = "error",
      error = paste("Could not load model:", model$message)
    ))
  }

  new_data <- tryCatch(
    as.data.frame(input_data, check.names = FALSE),
    error = function(e) e
  )

  if (inherits(new_data, "error")) {
    return(list(
      status = "error",
      error = paste("Invalid input data:", new_data$message)
    ))
  }

  prediction <- tryCatch(
    predict(model, newdata = new_data),
    error = function(e) e
  )

  if (inherits(prediction, "error")) {
    return(list(
      status = "prediction_error",
      error = paste(
        "Prediction failed. Check that the input feature names",
        "match the training data:", prediction$message
      )
    ))
  }

  list(
    status = "success",
    model = "Decision Tree Regression",
    prediction = as.numeric(prediction)[1],
    unit = "dataset target units",
    note = "This prediction is generated by the saved R model."
  )
}
